Enable mcmtools integration.

diff --git a/scripts/buildcross b/scripts/buildcross
--- a/scripts/buildcross
+++ b/scripts/buildcross
@@ -2,23 +2,28 @@
 
 HERE=$(dirname $(readlink -f ${0}))
 
-LIST=${HERE}/triples.txt
 LOGS=${HERE}/../logs
 BINS=${HERE}/../output
+OBJS=${HERE}/../build
 
 CSUF=cross
+NSUF=native
 
 KALE="${PATH}"
 
 mkdir -p ${LOGS} ${BINS}
-for t in $(cat ${LIST} | grep -v "#"); do
-    [ -d ${BINS}/${t}-${CSUF} ] || make -O install \
-        TARGET=${t} OUTPUT=${BINS}/${t}-${CSUF} \
-        -j$(nproc) 2>&1 | tee ${LOGS}/${t}-${CSUF}.log
-done;
 
-cd ${BINS}
-for t in $(find . -mindepth 1 -maxdepth 1 -type d); do
-    [ -h ${t}/usr ] || cd ${t} && ln -s . usr && cd ${BINS}
-    [ -e ${t}.tgz ] || tar pczf ${t}.tgz ${t};
-done
+# CROSS BUILD
+[ -d ${BINS}/${1}-${CSUF} ] || make install \
+    TARGET=${1} OUTPUT=${BINS}/${1}-${CSUF} \
+    -j$(nproc) 2>&1 | tee ${LOGS}/${1}-${CSUF}.log
+
+# CROSS PACKAGE
+[ -h ${BINS}/${1}-${CSUF}/usr ] || (cd ${BINS}/${1}-${CSUF} && ln -s . usr)
+[ -e ${BINS}/${1}-${CSUF}.tgz ] || (cd ${BINS} && tar pczf ${1}-${CSUF}.tgz ${1}-${CSUF})
+
+# CROSS CLEANUP
+rm -fr ${OBJS}/local/${1}
+
+# DIRECTORY CLEANUP
+rm -fr ${BINS}/${1}-${CSUF};
